const sampleCases = [
  {
    caseType: "Civil",
    courtType: "District Court",
    caseNumber: "DC/CIV/2024/001",
    petitioner: "Ramesh Sharma",
    respondent: "Suresh Verma",
    stage: "Evidence",
    nextHearingDate: new Date("2025-01-10"),
    timeSlot: "10:30 AM - 11:00 AM",
    courtFee: 1500,
    status: "Pending",
    affidavitId: 101,
    vakalatnamaNumber: 501
  },
  {
    caseType: "Criminal",
    courtType: "Sessions Court",
    caseNumber: "SC/CR/2024/002",
    petitioner: "State of Maharashtra",
    respondent: "Amit Patil",
    stage: "Arguments",
    nextHearingDate: new Date("2025-01-10"),
    timeSlot: "11:00 AM - 11:30 AM",
    courtFee: 0,
    status: "Pending",
    affidavitId: 102,
    vakalatnamaNumber: 502
  },
  {
    caseType: "Family",
    courtType: "Family Court",
    caseNumber: "FC/FAM/2024/003",
    petitioner: "Neha Kulkarni",
    respondent: "Rahul Kulkarni",
    stage: "Mediation",
    nextHearingDate: new Date("2025-01-11"),
    timeSlot: "12:00 PM - 12:30 PM",
    courtFee: 800,
    status: "Pending",
    affidavitId: 103,
    vakalatnamaNumber: 503
  },
  {
    caseType: "Civil",
    courtType: "High Court",
    caseNumber: "HC/CIV/2024/004",
    petitioner: "Anil Deshmukh",
    respondent: "Municipal Corporation",
    stage: "Admission",
    nextHearingDate: new Date("2025-01-11"),
    timeSlot: "10:00 AM - 10:30 AM",
    courtFee: 3000,
    status: "Pending",
    affidavitId: 104,
    vakalatnamaNumber: 504
  },
  {
    caseType: "Criminal",
    courtType: "Magistrate Court",
    caseNumber: "MC/CR/2024/005",
    petitioner: "State of India",
    respondent: "Karan Mehta",
    stage: "Charge Framing",
    nextHearingDate: new Date("2025-01-12"),
    timeSlot: "11:30 AM - 12:00 PM",
    courtFee: 0,
    status: "Pending",
    affidavitId: 105,
    vakalatnamaNumber: 505
  },

  // ---------- 6–15 ----------
  {
    caseType: "Civil",
    courtType: "District Court",
    caseNumber: "DC/CIV/2024/006",
    petitioner: "Sunita Pawar",
    respondent: "Mahesh Pawar",
    stage: "Final Arguments",
    nextHearingDate: new Date("2025-01-12"),
    timeSlot: "12:30 PM - 01:00 PM",
    courtFee: 1200,
    status: "Pending",
    affidavitId: 106,
    vakalatnamaNumber: 506
  },
  {
    caseType: "Criminal",
    courtType: "Sessions Court",
    caseNumber: "SC/CR/2024/007",
    petitioner: "State of Maharashtra",
    respondent: "Imran Khan",
    stage: "Cross Examination",
    nextHearingDate: new Date("2025-01-13"),
    timeSlot: "10:30 AM - 11:00 AM",
    courtFee: 0,
    status: "Pending",
    affidavitId: 107,
    vakalatnamaNumber: 507
  },
  {
    caseType: "Consumer",
    courtType: "Consumer Court",
    caseNumber: "CC/CON/2024/008",
    petitioner: "Priya Malhotra",
    respondent: "XYZ Electronics Ltd.",
    stage: "Evidence",
    nextHearingDate: new Date("2025-01-13"),
    timeSlot: "11:00 AM - 11:30 AM",
    courtFee: 500,
    status: "Pending",
    affidavitId: 108,
    vakalatnamaNumber: 508
  },
  {
    caseType: "Civil",
    courtType: "High Court",
    caseNumber: "HC/CIV/2024/009",
    petitioner: "TechNova Pvt Ltd",
    respondent: "Income Tax Dept.",
    stage: "Hearing",
    nextHearingDate: new Date("2025-01-14"),
    timeSlot: "12:00 PM - 12:30 PM",
    courtFee: 5000,
    status: "Pending",
    affidavitId: 109,
    vakalatnamaNumber: 509
  },
  {
    caseType: "Family",
    courtType: "Family Court",
    caseNumber: "FC/FAM/2024/010",
    petitioner: "Aarti Singh",
    respondent: "Rohit Singh",
    stage: "Counselling",
    nextHearingDate: new Date("2025-01-14"),
    timeSlot: "01:00 PM - 01:30 PM",
    courtFee: 700,
    status: "Pending",
    affidavitId: 110,
    vakalatnamaNumber: 510
  },

  // ---------- 16–30 ----------
  {
    caseType: "Civil",
    courtType: "District Court",
    caseNumber: "DC/CIV/2024/011",
    petitioner: "Vikas Jain",
    respondent: "Anita Jain",
    stage: "Order",
    nextHearingDate: new Date("2025-01-15"),
    timeSlot: "10:00 AM - 10:30 AM",
    courtFee: 1000,
    status: "Disposed",
    affidavitId: 111,
    vakalatnamaNumber: 511
  },
  {
    caseType: "Criminal",
    courtType: "Sessions Court",
    caseNumber: "SC/CR/2024/012",
    petitioner: "State of India",
    respondent: "Rohit Yadav",
    stage: "Judgement",
    nextHearingDate: new Date("2025-01-15"),
    timeSlot: "11:30 AM - 12:00 PM",
    courtFee: 0,
    status: "Disposed",
    affidavitId: 112,
    vakalatnamaNumber: 512
  },
  {
    caseType: "Consumer",
    courtType: "Consumer Court",
    caseNumber: "CC/CON/2024/013",
    petitioner: "Aakash Verma",
    respondent: "ABC Telecom",
    stage: "Arguments",
    nextHearingDate: new Date("2025-01-16"),
    timeSlot: "12:30 PM - 01:00 PM",
    courtFee: 400,
    status: "Pending",
    affidavitId: 113,
    vakalatnamaNumber: 513
  },
  {
    caseType: "Civil",
    courtType: "High Court",
    caseNumber: "HC/CIV/2024/014",
    petitioner: "GreenBuild Constructions",
    respondent: "State Government",
    stage: "Final Hearing",
    nextHearingDate: new Date("2025-01-16"),
    timeSlot: "01:00 PM - 01:30 PM",
    courtFee: 6000,
    status: "Pending",
    affidavitId: 114,
    vakalatnamaNumber: 514
  },
  {
    caseType: "Criminal",
    courtType: "Magistrate Court",
    caseNumber: "MC/CR/2024/015",
    petitioner: "State of Maharashtra",
    respondent: "Nikhil Joshi",
    stage: "Summons",
    nextHearingDate: new Date("2025-01-17"),
    timeSlot: "10:30 AM - 11:00 AM",
    courtFee: 0,
    status: "Pending",
    affidavitId: 115,
    vakalatnamaNumber: 515
  }
];

module.exports = sampleCases;